name: Lint
on:
  pull_request:
    branches: [main, dev]

jobs:
  front-end:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn

      - name: Run lint
        run: yarn lint

      - name: Run format
        run: yarn format

      - name: Run lint:fs
        run: yarn lint:fs

      - name: Run build
        run: yarn build

  back-end:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back-end
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn

      - name: Run lint
        run: yarn lint

      - name: Run format
        run: yarn format

      - name: Run lint:fs
        run: yarn lint:fs

      - name: Run build
        run: yarn build
